target("sdust.test.autogen_meta")
    set_default(false)
    set_kind("headeronly")
    add_includedirs("meta", { public = true })
    add_headerfiles("meta/**.hpp")

target("sdust.test.autogen_lib1")
    set_default(false)
    set_kind("static")
    add_includedirs("test1", { public = true })
    add_files("test1/**.cpp")
    add_deps("sdust.test.autogen_meta")

target_component_autogen("sdust.test.autogen_lib1")
    add_files("test1/**.h")
    add_rules("sdust.tmpl.test")

target("sdust.test.autogen_lib2")
    set_default(false)
    set_kind("static")
    add_includedirs("test2", { public = true })
    add_files("test2/**.cpp")
    add_deps("sdust.test.autogen_meta")

target_component_autogen("sdust.test.autogen_lib2", "autogen")
    add_files("test2/**.h")
    add_rules("sdust.tmpl.test")

target("sdust.test.autogen")
    add_rules("sdust.test")
    add_deps("sdust.test.autogen_lib1", "sdust.test.autogen_lib2")
    add_files("main.cpp")
