rule("sdust.tmpl.base")
    set_extensions(".h", ".hpp")
    add_imports("xcpp.autogen")
    on_config(function (target)
        autogen.setup(target)
    end)
    on_clean(function (target)
        autogen.clean(target)
    end)
