target("test_xcpp_lib1")
    set_default(false)
    set_kind("static")
    add_includedirs("test1", { public = true })
    add_files("test1/**.cpp")

target_component("test_xcpp_lib1", "autogen")
    set_kind("headeronly")
    add_files("test1/**.h")
    set_values("rootdir", "test1")
    add_values("tmpls", "xcpp.tmpl.test")
    add_rules("xcpp.autogen")

target("test_xcpp_lib2")
    set_default(false)
    set_kind("static")
    add_includedirs("test2", { public = true })
    add_files("test2/**.cpp")

target_component("test_xcpp_lib2", "autogen")
    set_kind("headeronly")
    add_files("test2/**.h")
    set_values("rootdir", "test2")
    add_values("tmpls", "xcpp.tmpl.test")
    add_rules("xcpp.autogen")

target("test_xcpp")
    add_rules("sdust.test")
    add_deps("test_xcpp_lib1", "test_xcpp_lib2")
    add_files("main.cpp")
