target_scoped("framework", "test")
    set_default(false)
    set_kind("headeronly")
    add_includedirs("include", { public = true })
    add_headerfiles("include/*.h")

rule("sdust.test")
    on_load(function (target)
        target:set("default", false)
        target:set("kind", "binary")
        target:add("deps", "test.framework")
        target:add("defines", "DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN")
        target:add("tests", "default", { runargs = { "-nv", "-ni" } })
    end)
