rule("sdust.tmpl")
    set_extensions(".h", ".hpp")
    add_imports("xcpp.autogen")
    on_config(function (target)
        autogen.setup(target)
    end)
    on_clean(function (target)
        autogen.clean(target)
    end)

rule("sdust.test")
    on_load(function (target)
        target:set("default", false)
        target:set("kind", "binary")
        target:add("deps", "test_framework")
        target:add("defines", "DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN")
        target:add("tests", "default", { runargs = { "-nv", "-ni" } })
    end)
