target_scoped("autogen_meta", "test")
    set_default(false)
    set_kind("headeronly")
    add_includedirs("meta", { public = true })
    add_headerfiles("meta/**.hpp")

target_scoped("autogen_lib1", "test")
    set_default(false)
    set_kind("static")
    add_includedirs("test1", { public = true })
    add_files("test1/**.cpp")
    add_deps("test.autogen_meta")

target_component_autogen("test.autogen_lib1")
    add_files("test1/**.h")
    add_rules("sdust.tmpl.test")

target_scoped("autogen_lib2", "test")
    set_default(false)
    set_kind("static")
    add_includedirs("test2", { public = true })
    add_files("test2/**.cpp")
    add_deps("test.autogen_meta")

target_component_autogen("test.autogen_lib2")
    add_files("test2/**.h")
    add_rules("sdust.tmpl.test")

target_scoped("autogen", "test")
    add_rules("sdust.test")
    add_deps("test.autogen_lib1", "test.autogen_lib2")
    add_files("main.cpp")
