rule("sdust.test")
    on_load(function (target)
        target:set("default", false)
        target:set("kind", "binary")
        target:add("deps", "test_framework")
        target:add("defines", "DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN")
        target:add("tests", "default", { runargs = { "-nv", "-ni" } })
    end)
