rule("xcpp.autogen")
    set_extensions(".h", "hpp")
    on_config(function (target)
        import("xcpp.module").autogen_setup(target)
    end)
    before_build(function (target)
        import("xcpp.module").autogen_process(target)
    end)
    on_clean(function (target)
        import("xcpp.module").autogen_clean(target)
    end)
