target("text_xcpp_meta")
    set_default(false)
    set_kind("headeronly")
    add_includedirs("meta", { public = true })
    add_headerfiles("meta/**.hpp")

target("test_xcpp_lib1")
    set_default(false)
    set_kind("static")
    add_includedirs("test1", { public = true })
    add_files("test1/**.cpp")
    add_deps("text_xcpp_meta")

target_component_autogen("test_xcpp_lib1")
    add_files("test1/**.h")
    set_values("rootdir", "test1")
    add_values("tmpls", "xcpp.tmpl.test")

target("test_xcpp_lib2")
    set_default(false)
    set_kind("static")
    add_includedirs("test2", { public = true })
    add_files("test2/**.cpp")
    add_deps("text_xcpp_meta")

target_component_autogen("test_xcpp_lib2")
    add_files("test2/**.h")
    set_values("rootdir", "test2")
    add_values("tmpls", "xcpp.tmpl.test")

target("test_xcpp")
    add_rules("sdust.test")
    add_deps("test_xcpp_lib1", "test_xcpp_lib2")
    add_files("main.cpp")
